version: '3.8'

services:
  server-soft-kpi:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=5000
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
